Algoritmo "aritmética"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2021
Var
// Seção de Declarações das variáveis 
 n1,n2,n3,media: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   n1 <- 10

   n2 <- 8

   n3 <- 7.5

   media <- (n1+n2+n3) /3

   escreva(media)

Fimalgoritmo