Algoritmo "concatenação"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2021
Var
// Seção de Declarações das variáveis 
   nome:caractere
   idade:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite seu nome: ")
   leia(nome)
   escreva ("Qual sua idade: ")
   leia(idade)
   escreva(nome," você tem ",idade," anos ")

Fimalgoritmo