Algoritmo "condicionais"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/02/2021
Var
// Seção de Declarações das variáveis 
   idade:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe a sua idade: ")
   leia(idade)
   se idade >=18 entao
      escreva("Você é Maior de Idade!")
      senao
      escreva("Você é Menor de Idade!")
   fimse

Fimalgoritmo