Algoritmo "expressoeslogicas"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2021
Var
// Seção de Declarações das variáveis 
a,b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- 2
   b <- 3
   escreval (a + b = 6)
   escreval (a + b = 5)
   escreval (a > b)
   escreval (a <> b)
   escreval (a = b)
   escreval (a >= b)


Fimalgoritmo