Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/02/2021
Var
// Seção de Declarações das variáveis 
 idade:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Escreval("Informe sua idade")
     leia(idade)
    se (idade >= 18) entao
   escreva (" Você é maior de idade!")
senao
   escreva ("Você é menor de idade!")
fimse

Fimalgoritmo