Algoritmo "triplo"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/02/2021
Var
// Seção de Declarações das variáveis 
numero: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero <- -1

enquanto ( numero <> 0) faca

escreva(" Digite um número: ")

leia(numero)

escreva(" Triplo: " , numero*3)

fimenquanto

fimalgoritmo